version: '3.8'

services:
  # --- Database Service ---
  postgres-db:
    image: postgres:15-alpine
    container_name: chat-app-db
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chat-network

  # --- Spring Boot Application Service ---
  app:
    container_name: chat-app-backend
    image: hotiovip/chat_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/chat_db
      SPRING_DATASOURCE_USERNAME: chat_user
      SPRING_DATASOURCE_PASSWORD: chat_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db
    networks:
      - chat-network

volumes:
  pgdata:

networks:
  chat-network: